In [27]:
#2588
a = int(input())
b = input()
c = a*int(b[2])
d=a*int(b[1])
e=a*int(b[0])
f=a*int(b)
print(c,d,e,f)

2360 3776 1416 181720


In [6]:
# 선생님답
m, n = map(int, input().split())
print(f'3: {m * ((n //1) % 10)}')       # ==>1의 자리 (n // 10 ** 0) % 10
print(f'4: {m * ((n //10) % 10)}')      # ==> 10의 자리  (n // 10 ** 1) % 10
print(f'5: {m * ((n //100) % 10)}')     # ==> 100의 자리 (n // 10 ** 2) % 10
print(f'6: {m * n}')

3: 2360
4: 3776
5: 1416
6: 181720


In [39]:
#25304
x = int(input()) #영수증에 적힌 총금액
n = int(input()) #영수증에 적힌 구매 물건 갯수
sum = 0

for i in range(n):
    a, b = map(int,input().split()) #각 물건의 가격 a, 갯수 b
    sum += a*b

if x == sum:
    print('Yes')
else:
    print('No')

No


In [ ]:
# 선생님 답
x = int(input())
n = int(input())
rec = []

for i in range(n):
    a, b = map(int,input().split()) 
    rec.append(a,b)

sum = 0
for a, b in rec:
        sum += a*b

In [83]:
#2562
a = [int(input()) for i in range(9)]    #9번을 반복해서 입력받기!
max_val = 0
for i in a:
    if i > max_val:
        max_val = i
print(max_val)
print(a.index(max(a))+1)

85
8


In [8]:
c = [3, 29, 38, 12, 57, 74, 40, 85, 61]
cmax, cindex = -1, -1
for index, element in enumerate(c):
    if cmax < element:
        cmax = element
        cindex = index
print(f'index={cindex}, {cindex+1}번째 값, {cmax}')

index=7, 8번째 값, 85


In [166]:
#2675

t = int(input())
for i in range(t):
    r, s = input().split()
    for k in s:     
        print(k*int(r), end='')
    print()

AAABBBCCC
/////HHHHHTTTTTPPPPP


In [9]:
#선생님 답
t = int(input())
test_case = []
for _ in range(t):
    cmd = input().split()
    test_case.append(cmd)
print(test_case)

for R, S in test_case:
    result =''
    r = int(R)
    for s in S:
        result += s * r
    print(result)

[['3', 'ABC'], ['5', '/HTP']]
AAABBBCCC
/////HHHHHTTTTTPPPPP


In [105]:
#10809
a = input()
alpha =('abcdefghijklmnopqrstuvwxyz')
for i in alpha:
    print(a.find(i), end=' ')

1 0 -1 -1 2 -1 -1 -1 -1 4 3 -1 -1 7 5 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 

In [ ]:
# 선생님 답
chr(ord('a')+1) # ==> b가 나옴

In [11]:
char_dic = {}
for i in range (26):     #알파벳 26자
    c = chr(ord('a')+i)    #알파벳 26자가 나옴
    char_dic[c] = -1
print(char_dic)

{'a': -1, 'b': -1, 'c': -1, 'd': -1, 'e': -1, 'f': -1, 'g': -1, 'h': -1, 'i': -1, 'j': -1, 'k': -1, 'l': -1, 'm': -1, 'n': -1, 'o': -1, 'p': -1, 'q': -1, 'r': -1, 's': -1, 't': -1, 'u': -1, 'v': -1, 'w': -1, 'x': -1, 'y': -1, 'z': -1}


In [12]:
word = 'baekjoon'
for i in range (26):
    c = chr(ord('a')+i)
    print(word.find(c), end=' ')        #a~z 까지 있는지 없는지 유무를 확인, 있으면 숫자, 없으면 -1

1 0 -1 -1 2 -1 -1 -1 -1 4 3 -1 -1 7 5 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 

In [14]:
char_dic = {}
word = 'a quick brown fox'
for i in range (26):
    c = chr(ord('a')+i)
    char_dic[c] = word.find(c)      #find()는 찾는 문자열이 없으면 -1을 리턴함
print(char_dic)

{'a': 0, 'b': 8, 'c': 5, 'd': -1, 'e': -1, 'f': 14, 'g': -1, 'h': -1, 'i': 4, 'j': -1, 'k': 6, 'l': -1, 'm': -1, 'n': 12, 'o': 10, 'p': -1, 'q': 2, 'r': 9, 's': -1, 't': -1, 'u': 3, 'v': -1, 'w': 11, 'x': 16, 'y': -1, 'z': -1}


In [ ]:
#세희 답
s =  input()
a = 'abcdefghijklmnopqrstuvwxyz'
for i in a:
    if i in s:
        print(s.index(i), end= ' ')  #=> s의 인덱스값을 
    else:
        print(-1, end= ' ')

In [125]:
#2908
a, b = input().split()
a = int(a[::-1])
b = int(b[::-1])
if a > b:
    print(a)
else:
    print(b)

938


In [15]:
#선생님 답
for i in range(3):
    m, n = input().split()
    m_, n_ = int(m[::-1]), int(n[::-1])
    max_val = m_ if m_ >= n_ else n_
    print(f'{m}, {n}: {max_val}')

734, 893: 437
221, 231: 132
839, 237: 938


In [157]:
#3003
c = [1, 1, 2, 2, 2, 8]
a = list(map(int,input().split()))
for i in range(len(c)):
    print(c[i]-a[i], end=' ')


-1 0 0 1 0 7 

In [16]:
# 선생님 답
# king, queen, rook, bishop, knight, pawn
cp = [1, 1, 2, 2, 2, 8]
p = list(map(int,input().split()))
for i in range(len(cp)):
    print(cp[i] - p[i], end=' ')

-1 1 -2 1 -1 3 

In [140]:
#2444
n = int(input())
for i in range(1,n):
    print(' '*(n-i)+'*'*(i*2-1))
for i in range(n,0,-1):     #위, 중간, 아래
    print(' '*(n-i)+'*'*(i*2-1))


    *
   ***
  *****
 *******
*********
 *******
  *****
   ***
    *


In [20]:
# 선생님 답
n = 5
for i in range(n):
    line = ' ' * (n-i-1) + '*'*(2*i+1)
    print(line)
for i in range(1,n):
    line = ' ' * i  + '*'*(2*(n-i)-1)
    print(line)

    *
   ***
  *****
 *******
*********
 *******
  *****
   ***
    *


In [149]:
#1157       ==check
s = list(input())
#d = {str:i for i, str in enumerate(s)}

s.sort(reverse=True)
s

NameError: name 'count' is not defined

In [25]:
#선생님 답
al_dic = {}
s = 'A quick brown fox jumps over the lazy dog'
for i in range(26):
    c = chr(ord('a') + i)
    al_dic[c] = s.lower().count(c)
print(al_dic)
al_items = list(al_dic.items())
al_items.sort(key=lambda x: x[1], reverse=True)
al_items[:4]        #가장많이 사용된 단어

{'a': 2, 'b': 1, 'c': 1, 'd': 1, 'e': 2, 'f': 1, 'g': 1, 'h': 1, 'i': 1, 'j': 1, 'k': 1, 'l': 1, 'm': 1, 'n': 1, 'o': 4, 'p': 1, 'q': 1, 'r': 2, 's': 1, 't': 1, 'u': 2, 'v': 1, 'w': 1, 'x': 1, 'y': 1, 'z': 1}


[('o', 4), ('a', 2), ('e', 2), ('r', 2)]

In [27]:
#2738, 선생님 답
a = [[1,1,1],[2,2,2],[0,1,0]]
b = [[3,3,3],[4,4,4],[5,5,100]]
c = []
for i in range(len(a)):
    temp = []
    for k in range(len(a[i])):
        temp.append(a[i][k] + b[i][k])
    c.append(temp)

for i in range(len(c)):
    for k in range(len(c[i])):
        print(c[i][k], end=' ')
    print()       

4 4 4 
6 6 6 
5 6 100 


In [28]:
c = [[0,0,0],[0,0,0],[0,0,0]]       #이미 규격이 정해져있으면, 아예 0으로 초기화
for i in range(len(a)):
    for k in range(len(a[i])):
        c[i][k]=a[i][k] + b[i][k]

for i in range(len(c)):
    for k in range(len(c[i])):
        print(c[i][k], end=' ')
    print()     

4 4 4 
6 6 6 
5 6 100 


- Numpy를 사용해야 하는 이유

In [29]:
import numpy as np              #numpy 사용!
a = np.array([[1,1,1],[2,2,2],[0,1,0]])
print(a)

[[1 1 1]
 [2 2 2]
 [0 1 0]]


In [30]:
b= np.array([[3,3,3],[4,4,4],[5,5,100]])
print(b)

[[  3   3   3]
 [  4   4   4]
 [  5   5 100]]


In [31]:
# 벡터화 연산
c = a+b
print(c)

[[  4   4   4]
 [  6   6   6]
 [  5   6 100]]
